// Generated by gencpp from file ros_assignment_1/VectorOutput.msg
// DO NOT EDIT!


#ifndef ROS_ASSIGNMENT_1_MESSAGE_VECTOROUTPUT_H
#define ROS_ASSIGNMENT_1_MESSAGE_VECTOROUTPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_assignment_1
{
template <class ContainerAllocator>
struct VectorOutput_
{
  typedef VectorOutput_<ContainerAllocator> Type;

  VectorOutput_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  VectorOutput_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::ros_assignment_1::VectorOutput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_assignment_1::VectorOutput_<ContainerAllocator> const> ConstPtr;

}; // struct VectorOutput_

typedef ::ros_assignment_1::VectorOutput_<std::allocator<void> > VectorOutput;

typedef boost::shared_ptr< ::ros_assignment_1::VectorOutput > VectorOutputPtr;
typedef boost::shared_ptr< ::ros_assignment_1::VectorOutput const> VectorOutputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_assignment_1::VectorOutput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_assignment_1::VectorOutput_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_assignment_1::VectorOutput_<ContainerAllocator1> & lhs, const ::ros_assignment_1::VectorOutput_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_assignment_1::VectorOutput_<ContainerAllocator1> & lhs, const ::ros_assignment_1::VectorOutput_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_assignment_1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_assignment_1::VectorOutput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_assignment_1::VectorOutput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_assignment_1::VectorOutput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_assignment_1::VectorOutput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_assignment_1::VectorOutput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_assignment_1::VectorOutput_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_assignment_1::VectorOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::ros_assignment_1::VectorOutput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a842b65f413084dULL;
  static const uint64_t static_value2 = 0xc2b10fb484ea7f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_assignment_1::VectorOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_assignment_1/VectorOutput";
  }

  static const char* value(const ::ros_assignment_1::VectorOutput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_assignment_1::VectorOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::ros_assignment_1::VectorOutput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_assignment_1::VectorOutput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VectorOutput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_assignment_1::VectorOutput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_assignment_1::VectorOutput_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ASSIGNMENT_1_MESSAGE_VECTOROUTPUT_H
