// Generated by gencpp from file ros_assignment_1/VectorInput.msg
// DO NOT EDIT!


#ifndef ROS_ASSIGNMENT_1_MESSAGE_VECTORINPUT_H
#define ROS_ASSIGNMENT_1_MESSAGE_VECTORINPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_assignment_1
{
template <class ContainerAllocator>
struct VectorInput_
{
  typedef VectorInput_<ContainerAllocator> Type;

  VectorInput_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , alpha(0.0)
    , beta(0.0)
    , gamma(0.0)
    , dx(0.0)
    , dy(0.0)
    , dz(0.0)  {
    }
  VectorInput_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , alpha(0.0)
    , beta(0.0)
    , gamma(0.0)
    , dx(0.0)
    , dy(0.0)
    , dz(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _alpha_type;
  _alpha_type alpha;

   typedef double _beta_type;
  _beta_type beta;

   typedef double _gamma_type;
  _gamma_type gamma;

   typedef double _dx_type;
  _dx_type dx;

   typedef double _dy_type;
  _dy_type dy;

   typedef double _dz_type;
  _dz_type dz;





  typedef boost::shared_ptr< ::ros_assignment_1::VectorInput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_assignment_1::VectorInput_<ContainerAllocator> const> ConstPtr;

}; // struct VectorInput_

typedef ::ros_assignment_1::VectorInput_<std::allocator<void> > VectorInput;

typedef boost::shared_ptr< ::ros_assignment_1::VectorInput > VectorInputPtr;
typedef boost::shared_ptr< ::ros_assignment_1::VectorInput const> VectorInputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_assignment_1::VectorInput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_assignment_1::VectorInput_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_assignment_1::VectorInput_<ContainerAllocator1> & lhs, const ::ros_assignment_1::VectorInput_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.alpha == rhs.alpha &&
    lhs.beta == rhs.beta &&
    lhs.gamma == rhs.gamma &&
    lhs.dx == rhs.dx &&
    lhs.dy == rhs.dy &&
    lhs.dz == rhs.dz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_assignment_1::VectorInput_<ContainerAllocator1> & lhs, const ::ros_assignment_1::VectorInput_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_assignment_1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_assignment_1::VectorInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_assignment_1::VectorInput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_assignment_1::VectorInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_assignment_1::VectorInput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_assignment_1::VectorInput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_assignment_1::VectorInput_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_assignment_1::VectorInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "62b38fb50e34d3bc1ef194d47c852b37";
  }

  static const char* value(const ::ros_assignment_1::VectorInput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x62b38fb50e34d3bcULL;
  static const uint64_t static_value2 = 0x1ef194d47c852b37ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_assignment_1::VectorInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_assignment_1/VectorInput";
  }

  static const char* value(const ::ros_assignment_1::VectorInput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_assignment_1::VectorInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 alpha\n"
"float64 beta\n"
"float64 gamma\n"
"float64 dx\n"
"float64 dy\n"
"float64 dz\n"
;
  }

  static const char* value(const ::ros_assignment_1::VectorInput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_assignment_1::VectorInput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.alpha);
      stream.next(m.beta);
      stream.next(m.gamma);
      stream.next(m.dx);
      stream.next(m.dy);
      stream.next(m.dz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VectorInput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_assignment_1::VectorInput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_assignment_1::VectorInput_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "alpha: ";
    Printer<double>::stream(s, indent + "  ", v.alpha);
    s << indent << "beta: ";
    Printer<double>::stream(s, indent + "  ", v.beta);
    s << indent << "gamma: ";
    Printer<double>::stream(s, indent + "  ", v.gamma);
    s << indent << "dx: ";
    Printer<double>::stream(s, indent + "  ", v.dx);
    s << indent << "dy: ";
    Printer<double>::stream(s, indent + "  ", v.dy);
    s << indent << "dz: ";
    Printer<double>::stream(s, indent + "  ", v.dz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ASSIGNMENT_1_MESSAGE_VECTORINPUT_H
