# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_assignment_1/vector_in.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class vector_in(genpy.Message):
  _md5sum = "c3f752c00d0fcadb1566ee98436f6d75"
  _type = "ros_assignment_1/vector_in"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point vector
geometry_msgs/Point angle
float64 distance
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['vector','angle','distance']
  _slot_types = ['geometry_msgs/Point','geometry_msgs/Point','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vector,angle,distance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(vector_in, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.vector is None:
        self.vector = geometry_msgs.msg.Point()
      if self.angle is None:
        self.angle = geometry_msgs.msg.Point()
      if self.distance is None:
        self.distance = 0.
    else:
      self.vector = geometry_msgs.msg.Point()
      self.angle = geometry_msgs.msg.Point()
      self.distance = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.vector.x, _x.vector.y, _x.vector.z, _x.angle.x, _x.angle.y, _x.angle.z, _x.distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.vector is None:
        self.vector = geometry_msgs.msg.Point()
      if self.angle is None:
        self.angle = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.vector.x, _x.vector.y, _x.vector.z, _x.angle.x, _x.angle.y, _x.angle.z, _x.distance,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.vector.x, _x.vector.y, _x.vector.z, _x.angle.x, _x.angle.y, _x.angle.z, _x.distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.vector is None:
        self.vector = geometry_msgs.msg.Point()
      if self.angle is None:
        self.angle = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.vector.x, _x.vector.y, _x.vector.z, _x.angle.x, _x.angle.y, _x.angle.z, _x.distance,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
