# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from arm_lib/Angles.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Angles(genpy.Message):
  _md5sum = "d1b7ee805afcab3ec788a0b100202f1a"
  _type = "arm_lib/Angles"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 arm1_angle
float32 arm2_angle
float32 arm3_angle
float32 arm4_angle 
"""
  __slots__ = ['arm1_angle','arm2_angle','arm3_angle','arm4_angle']
  _slot_types = ['float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       arm1_angle,arm2_angle,arm3_angle,arm4_angle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Angles, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.arm1_angle is None:
        self.arm1_angle = 0.
      if self.arm2_angle is None:
        self.arm2_angle = 0.
      if self.arm3_angle is None:
        self.arm3_angle = 0.
      if self.arm4_angle is None:
        self.arm4_angle = 0.
    else:
      self.arm1_angle = 0.
      self.arm2_angle = 0.
      self.arm3_angle = 0.
      self.arm4_angle = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.arm1_angle, _x.arm2_angle, _x.arm3_angle, _x.arm4_angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.arm1_angle, _x.arm2_angle, _x.arm3_angle, _x.arm4_angle,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.arm1_angle, _x.arm2_angle, _x.arm3_angle, _x.arm4_angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.arm1_angle, _x.arm2_angle, _x.arm3_angle, _x.arm4_angle,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
